name       : podofo-09
version    : 0.9.8
release    : 1
source     :
    - https://github.com/podofo/podofo/archive/refs/tags/0.9.8.tar.gz : 2176e7281bdcd57769768eca30e7673257041bf7f092bfabfcdf85018b5dc7dc
homepage   : https://github.com/podofo/podofo
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
summary    : PoDoFo is a library to work with the PDF file format.
description: |
    The PoDoFo library is a free, portable C++ library which includes classes to parse PDF files and modify their contents into memory. The changes can be written back to disk easily. The parser can also be used to extract information from a PDF file (for example the parser could be used in a PDF viewer). Besides parsing PoDoFo includes also very simple classes to create your own PDF files. All classes are documented so it is easy to start writing your own application using PoDoFo.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(lua)
setup      : |
    %patch -p1 < $pkgfiles/dont-hardcode-install-dirs.patch

    # Fix include dir in pc file
    sed -e 's|@CMAKE_INSTALL_FULL_INCLUDEDIR@/podofo|@CMAKE_INSTALL_FULL_INCLUDEDIR@|' -i src/podofo/libpodofo.pc.in
    
    %cmake \
        -DCMAKE_INSTALL_LIBDIR=lib/podofo-09 \
        -DCMAKE_INSTALL_INCLUDEDIR=include/podofo-09 \
        -DFREETYPE_INCLUDE_DIR=/usr/include/freetype2 \
        -DCMAKE_INSTALL_PREFIX=/usr . \
        -DPODOFO_BUILD_SHARED=1 \
        -DPODOFO_HAVE_JPEG_LIB=1 \
        -DPODOFO_HAVE_PNG_LIB=1 \
        -DPODOFO_HAVE_TIFF_LIB=1 \
        -DPODOFO_BUILD_LIB_ONLY=1
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/lib/podofo-09/pkgconfig/{libpodofo.pc,libpodofo-09.pc}
check      : |
    %make test
